"use client";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useBirthRegistration } from "./context";
import { useEffect } from "react";

export function CertificateDelivery() {
	const { state, resetApplication, navigateTo } = useBirthRegistration();

	const handleDownloadDigital = () => {
		// Simulate download
		const link = document.createElement('a');
		link.href = 'data:text/plain;charset=utf-8,' + encodeURIComponent(`
CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM
Độc lập - Tự do - Hạnh phúc

GIẤY KHAI SINH / BIRTH CERTIFICATE

Số đăng ký: ${state.referenceCode || 'BRC-2025-001234'}
Registration Number: ${state.referenceCode || 'BRC-2025-001234'}

Scenario: ${state.selectedScenario?.nameVn || 'N/A'}
Authority: ${state.selectedScenario?.authorityVn || 'N/A'}

Ngày cấp: ${new Date().toLocaleDateString('vi-VN')}
Issue Date: ${new Date().toLocaleDateString('en-US')}

This is a digital birth certificate generated by the AI-powered system.
		`);
		link.download = `birth-certificate-${state.referenceCode || 'sample'}.txt`;
		document.body.appendChild(link);
		link.click();
		document.body.removeChild(link);

		// Show success message
		alert('Giấy khai sinh số đã được tải về!\nDigital birth certificate downloaded!');
	};

	const handleRequestPhysical = () => {
		alert('Yêu cầu bản giấy đã được gửi. Bạn sẽ nhận được thông báo khi sẵn sàng.\n\nPhysical copy request sent. You will be notified when ready.');
	};

	const handleStartNew = () => {
		resetApplication();
	};

	if (!state.selectedScenario) {
		return (
			<div className="p-8 text-center">
				<p>No scenario data available.</p>
				<Button onClick={() => navigateTo("landing")}>Return to Home</Button>
			</div>
		);
	}

	return (
		<div className="animate-fade-in">
			{/* Header */}
			<header className="bg-card border-b-2 border-primary py-4">
				<div className="container mx-auto px-6">
					<div className="flex items-center justify-between flex-wrap gap-4">
						<h1 className="text-2xl font-semibold vietnam-accent">
							Hoàn thành / Completion
						</h1>
						<div className="flex items-center gap-2">
							{Array.from({ length: 5 }, (_, i) => (
								<div
									key={i}
									className="w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold border-2 bg-green-500 text-white border-green-500"
								>
									{i + 1}
								</div>
							))}
						</div>
					</div>
				</div>
			</header>

			{/* Main Content */}
			<main className="container mx-auto px-6 py-8">
				<div className="max-w-4xl mx-auto space-y-8">
					{/* Success Message */}
					<Card className="border-green-200 bg-green-50 dark:bg-green-950 dark:border-green-800 text-center">
						<CardContent className="p-8">
							<div className="text-6xl mb-6">✅</div>
							<h2 className="text-3xl font-bold vietnam-accent mb-2">
								Đăng ký khai sinh thành công!
							</h2>
							<h3 className="text-xl text-muted-foreground mb-4">
								Birth Registration Completed Successfully!
							</h3>
							<p className="text-lg mb-2">
								Giấy khai sinh đã được tạo và sẵn sàng để tải về.
							</p>
							<p className="text-muted-foreground">
								Birth certificate has been generated and is ready for download.
							</p>
						</CardContent>
					</Card>

					{/* Scenario Completion Info */}
					<Card>
						<CardHeader>
							<CardTitle className="vietnam-accent flex items-center gap-2">
								<span>🎯</span>
								Thông tin hoàn thành / Completion Information
							</CardTitle>
						</CardHeader>
						<CardContent>
							<div className="grid md:grid-cols-2 gap-6">
								<div>
									<h4 className="font-semibold vietnam-accent mb-3">Scenario Processed:</h4>
									<p className="text-lg font-medium">{state.selectedScenario.name}</p>
									<p className="text-muted-foreground">{state.selectedScenario.nameVn}</p>
								</div>
								
								<div>
									<h4 className="font-semibold vietnam-accent mb-3">Processing Authority:</h4>
									<p className="text-lg font-medium">{state.selectedScenario.authority}</p>
									<p className="text-muted-foreground">{state.selectedScenario.authorityVn}</p>
								</div>
								
								<div>
									<h4 className="font-semibold vietnam-accent mb-3">Total Processing Time:</h4>
									<p className="text-lg font-medium">{state.selectedScenario.timeline}</p>
									<p className="text-muted-foreground">{state.selectedScenario.timelineVn}</p>
								</div>
								
								<div>
									<h4 className="font-semibold vietnam-accent mb-3">Complexity Level:</h4>
									<p className="text-lg font-medium">{state.selectedScenario.complexity}</p>
									<p className="text-muted-foreground">{state.selectedScenario.complexityVn}</p>
								</div>
							</div>
						</CardContent>
					</Card>

					{/* Certificate Preview */}
					<Card>
						<CardHeader>
							<CardTitle className="vietnam-accent">
								Xem trước giấy khai sinh / Certificate Preview
							</CardTitle>
						</CardHeader>
						<CardContent>
							<div className="bg-white border-2 border-primary rounded-lg p-8 text-black shadow-lg">
								{/* Certificate Header */}
								<div className="text-center mb-8 pb-6 border-b-2 border-primary">
									<div className="text-4xl mb-4">🇻🇳</div>
									<h4 className="text-lg font-bold text-primary mb-2">
										CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM
									</h4>
									<p className="text-sm text-gray-600 mb-4">Độc lập - Tự do - Hạnh phúc</p>
									<h3 className="text-xl font-bold text-primary">
										GIẤY KHAI SINH / BIRTH CERTIFICATE
									</h3>
								</div>

								{/* Certificate Content */}
								<div className="space-y-4">
									<div className="grid grid-cols-2 gap-4">
										<div>
											<p className="font-semibold">Số đăng ký:</p>
											<p className="text-sm text-gray-600">{state.referenceCode || 'BRC-2025-001234'}</p>
										</div>
										<div>
											<p className="font-semibold">Registration Number:</p>
											<p className="text-sm text-gray-600">{state.referenceCode || 'BRC-2025-001234'}</p>
										</div>
									</div>

									<div className="grid grid-cols-2 gap-4">
										<div>
											<p className="font-semibold">Kịch bản xử lý:</p>
											<p className="text-sm text-gray-600">{state.selectedScenario.nameVn}</p>
										</div>
										<div>
											<p className="font-semibold">Processing Scenario:</p>
											<p className="text-sm text-gray-600">{state.selectedScenario.name}</p>
										</div>
									</div>

									<div className="pt-4 text-right text-sm text-gray-600 italic">
										<p>Ngày cấp: {new Date().toLocaleDateString('vi-VN')}</p>
										<p>Issue Date: {new Date().toLocaleDateString('en-US')}</p>
									</div>
								</div>
							</div>
						</CardContent>
					</Card>

					{/* Delivery Options */}
					<Card>
						<CardHeader>
							<CardTitle className="vietnam-accent">
								Tùy chọn nhận / Delivery Options
							</CardTitle>
						</CardHeader>
						<CardContent>
							<div className="flex flex-col sm:flex-row gap-4 justify-center">
								<Button 
									size="lg"
									className="vietnam-primary flex items-center gap-2"
									onClick={handleDownloadDigital}
								>
									<span>📄</span>
									Tải về số / Download Digital
								</Button>
								<Button 
									size="lg"
									variant="outline"
									className="flex items-center gap-2"
									onClick={handleRequestPhysical}
								>
									<span>📮</span>
									Yêu cầu bản giấy / Request Physical Copy
								</Button>
							</div>
						</CardContent>
					</Card>

					{/* Reference Information */}
					<Card>
						<CardHeader>
							<CardTitle className="vietnam-accent">
								Thông tin tham chiếu / Reference Information
							</CardTitle>
						</CardHeader>
						<CardContent>
							<div className="bg-blue-50 dark:bg-blue-950 p-6 rounded-lg border border-blue-200 dark:border-blue-800">
								<div className="space-y-2">
									<p>
										<strong>Mã tham chiếu:</strong> {state.referenceCode || 'VN-BR-2025-08-26-001234'}
									</p>
									<p>
										<strong>Reference Code:</strong> {state.referenceCode || 'VN-BR-2025-08-26-001234'}
									</p>
									<p className="text-sm text-muted-foreground mt-4">
										Vui lòng lưu mã này để tra cứu sau.
									</p>
									<p className="text-sm text-muted-foreground">
										Please save this code for future reference.
									</p>
								</div>
							</div>
						</CardContent>
					</Card>

					{/* Completion Actions */}
					<div className="text-center">
						<Button 
							size="lg"
							className="vietnam-primary px-8 py-3"
							onClick={handleStartNew}
						>
							Đăng ký mới / New Registration
						</Button>
					</div>
				</div>
			</main>
		</div>
	);
}
